### ISSUE TITLE
a rock-paper-scissors script

### ISSUE THREAD

**Issue by linuxdotexe** [gdsc-gvp/Pyscripts#23]
# Aim

- What is the objective of the Script
a rock-paper-scissors script

# Details

a little script that implements rock-paper-scissors.
- What the features will your script have
It keeps score.

[here](https://gist.github.com/linuxdotexe/5bf3f6f231ac387b2e85657fbe82e881) is the code. assign it to me if you approve :)

Sorry for the empty issue at first, I didn't know `Ctrl+Enter` is a shortcut.

**Comment by rakesh0x7** [comment]
@linuxdotexe No worries! 😃
